### ISSUE TITLE
👨‍⚕️ QA: 로그인 하지 않은 상태로 리뷰 창 접근 가능

### ISSUE THREAD

**Issue by yoonseon12** [Kernel360/f1-JDON-Frontend#197]
로그인 하지 않은 상태로 리뷰 항목 선택 시 로그인창으로 이동합니다.

이동된 로그인창에서 뒤로가기버튼 클릭 시 리뷰가 선택된 화면으로 이동됩니다.(로그인 하지 않은 상태로 리뷰 등록 폼도 이동 가능함.)
물론 리뷰 목록 조회API, 리뷰등록 API는 로그인한 회원만 호출할 수 있도록 서버에 설정되있기 때문에 데이터는 보이지 않지만
사용자 입장에서 장애라고 판단될 것 같습니다 .

따라서 로그인 하지 않은 상태로 메인 화면의 찜 버튼을 클릭했을 때 출력되는 로그인 알림 메시지가 출력되었으면 좋겠습니다.

**Comment by junkue20** [comment]
@Wlfjd 
현재 제 로컬 & 배포페이지에서는 아래 부분처럼 로그인 상태를 잘 캐치하는 것 같은데, 
지원님 쪽에서 확인이 필요할 것 같네요.
![9](https://github.com/Kernel360/f1-JDON-Frontend/assets/122848687/536c2aa2-f723-4247-8bc9-2ab76e374f6e)

**Comment by Wlfjd** [comment]
흐음 윤선님께서 말씀하신 부분은 아마도..
로그인 상태를 잘 캐치해서 로그인 화면으로 보내기는 하지만 사용자가 뒤로가기를 클릭하면 리뷰 글쓰기 창이 열린다는 말씀인 것 같습니다

**커피챗 오픈**과 동일하게  로그인 알림 메시지가 출력되도록 할게요

 로그인에 대해서는 여러번 더 테스트를 해볼 필요가 있을 것 같습니다!

**Comment by Wlfjd** [comment]
해결하였습니다
