### ISSUE TITLE
👨‍⚕️ QA: 로그인 페이지에서 버튼 이름 수정하기 

### ISSUE THREAD

**Issue by anso33** [Kernel360/f1-JDON-Frontend#198]
### ✨ 작업 내용

- `~~ 로그인` 에서 `~~로 시작하기` 로 수정해주세요

![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/68376744/592b0821-5e75-4812-9444-a633f126fc09)

를 아래의 예시처럼 수정해주세요.

<img width="564" alt="image" src="https://github.com/Kernel360/f1-JDON-Frontend/assets/68376744/e6a543bc-3cb3-4d09-8b0d-8736333c1122">

### ⚙ 상세한 작업 내용

- [x] : 로그인 버튼 문구 수정
- [x] : 아이콘 간격 수정

### 🛠 예상 소요시간

None

**Comment by junkue20** [comment]
@anso33 QA감사합니다 소현님!
이부분은 제가 맡아서 바로 수정하겠습니다!

**Comment by junkue20** [comment]
@anso33 
https://github.com/Kernel360/f1-JDON-Frontend/pull/217
위 PR에 해당내용 반영했습니다.
