### ISSUE TITLE
👨‍⚕️ QA: 내 정보 페이지에서 직무 & 직군 선택 표시

### ISSUE THREAD

**Issue by anso33** [Kernel360/f1-JDON-Frontend#200]
### ✨ 작업 내용

내 정보 페이지에 들어가면 

![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/68376744/c17027d1-389d-4c81-8609-0b4105482e30)

이렇게 비어있는데 선택했던 직무, 직군을 표시하도록 수정해주세요.

추가로 사용자가 직무, 직군을 새로 선택하지 않으면 내 정보에 있는 직무, 직군 정보를 그대로 request body에 담아서 수정 요청 보내주세요.

### ⚙ 상세한 작업 내용

- [ ] :
- [ ] :
- [ ] : 

### 🛠 예상 소요시간

None

**Comment by junkue20** [comment]
![19](https://github.com/Kernel360/f1-JDON-Frontend/assets/122848687/112b5811-8c0f-40d8-bbbf-29353a991dc2)
배포사이트 확인해보니 해당부분 지원님께서 반영하신것으로 확인되어 해당 이슈는 닫도록 하겠습니다!
