### ISSUE TITLE
👨‍⚕️ QA: 마이페이지에서의 찜 취소

### ISSUE THREAD

**Issue by aacara** [Kernel360/f1-JDON-Frontend#202]
내가 찜한 목록에서 찜하기 버튼이 모두 켜져있거나 찜 취소 버튼이 별도로 있어야 할 것 같습니다.

현재 상황: 전구를 켰다가 끄면 화면에 다시 들어갈 때, 찜 취소가 되고 있지만, 다시 켜도 여전히 찜 취소가 반영되어있으므로 혼란스러움
해결 방안1: 전구 대신 찜 취소 버튼을 따로 두기
해결 방안2: 전구가 모두 켜져있는 상태에서 전구를 끄면 페이지에서 강의 정보가 바로 사라지도록 수정
![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/86637372/20606c67-1187-4f33-8301-c532d92dac6f)

**Comment by yoonseon12** [comment]
해결방안 1, 2중 하나가 적용되었을 때 찜 취소를 하는 버튼을 클릭하면 알림창이 뜨면 좋을 것 같습니다.

**Comment by anso33** [comment]
해결 방안 2로 반영되었으면 좋겠습니다

**Comment by junkue20** [comment]
![18](https://github.com/Kernel360/f1-JDON-Frontend/assets/122848687/83671191-89a9-4335-b5d0-6d33f4f0d224)
배포사이트 확인해보니 2안으로 지원님께서 반영하신 것 같아 해당 이슈 닫도록 하겠습니다!
