### ISSUE TITLE
👨‍⚕️ QA: 커피챗 모집 인원 상한선 필요 

### ISSUE THREAD

**Issue by aacara** [Kernel360/f1-JDON-Frontend#203]
### ✨ 작업 내용

~~마이페이지에서 내가 오픈한 커피챗에서~~ 커피챗 수정과 등록에서 총 모집 인원에 상한선(논의 필요) valdiation 필요
![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/86637372/fe33637e-0a1f-44b0-9001-1be1810edf43)

### ⚙ 상세한 작업 내용

- [ ] :
- [ ] :
- [ ] : 

### 🛠 예상 소요시간

None

**Comment by Wlfjd** [comment]
1~100 명으로 유효성 추가하였습니다
