### ISSUE TITLE
👨‍⚕️ QA: 이미 만료된 커피챗의 경우, 수정하기 버튼 비활성화 

### ISSUE THREAD

**Issue by aacara** [Kernel360/f1-JDON-Frontend#205]
### ✨ 작업 내용

이미 만료된 커피챗의 경우 수정페이지에서 수정하기를 누를 수 없도록 막아놓으면 좋을 것 같습니다.
![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/86637372/990f7a0d-b6ff-4e21-b851-0d8a8d7e3e4a)

### ⚙ 상세한 작업 내용

- [ ] :
- [ ] :
- [ ] : 

### 🛠 예상 소요시간

None

**Comment by aqrms** [comment]
상태가 모집중, 모집완료, 모집종료가 있는데 모집종료된 커피챗은 사용자가 조회할 수 없어서 수정이 불가합니다.
모집완료인 커피챗은 만약 사용자가 취소할 경우 다시 모집이 가능해질수 있기 때문에 수정에 열려있어야 할 것 같습니다..

**Comment by Wlfjd** [comment]
그럼 이 이슈는 닫아도 되는건가요??

**Comment by aacara** [comment]
넵, 닫아도 될 것 같습니다!
