### ISSUE TITLE
👨‍⚕️ QA: 내가 신청한 커피챗 상세 조회에서, 신청하기 버튼 -> 취소하기 버튼

### ISSUE THREAD

**Issue by aacara** [Kernel360/f1-JDON-Frontend#206]
### ✨ 작업 내용

신청하기가 아닌, 취소하기 버튼으로 바뀌고 삭제하는 기능으로 바뀌어야할 것 같습니다~
![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/86637372/6459e133-a5a8-4968-acaf-4707addadb68)

### ⚙ 상세한 작업 내용

- [ ] :
- [ ] :
- [ ] : 

### 🛠 예상 소요시간

None

**Comment by aqrms** [comment]
취소하기 API는 아직 구현되어 있지 않긴 합니다ㅎㅎ

**Comment by aqrms** [comment]
https://github.com/Kernel360/f1-JDON-Frontend/issues/210
현재 단계에서는 위 이슈에 따르는게 좋을 것 같슴다
