### ISSUE TITLE
👨‍⚕️ QA: 커피챗 등록 완료 시 리다이렉트

### ISSUE THREAD

**Issue by aacara** [Kernel360/f1-JDON-Frontend#207]
### ✨ 작업 내용

커피챗 등록 완료 시 아래 문구에 확인 버튼을 누르면, 
![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/86637372/b6cfe40e-8a67-47ee-9f49-d1a57f21bb83)
현재 `https://jdon.kr/mypage`로 이동중인데  `https://jdon.kr/mypage/coffee` 마이페이지 내의 커피챗 목록 페이지에서 '내가 신청한 커피챗'탭으로 이동하면 더 좋을 것 같습니다.

### ⚙ 상세한 작업 내용

- [ ] :
- [ ] :
- [ ] : 

### 🛠 예상 소요시간

None

**Comment by aqrms** [comment]
윤선님과 지원님과 논의했었습니다.
커피챗 등록 완료 시 유저가 확인 취소를 선택하도록 하지 않고 그냥 정상 등록완료 되었다는 알러트를 띄우고
작성완료된 커피챗 상세페이지로 리다이렉트 하는게 자연스러운 흐름 같습니다

**Comment by Wlfjd** [comment]
구현 완료하였습니다
