### ISSUE TITLE
👨‍⚕️ QA: 닉네임을 수정하진 않았지만 중복체크 확인을 누르면 내 정보 수정을 할 수 없음

### ISSUE THREAD

**Issue by anso33** [Kernel360/f1-JDON-Frontend#209]
### ✨ 작업 내용

내 닉네임을 수정하진 않았지만 중복버튼을 누르면 에러 처리로 떠서 더이상 수정 버튼을 누를 수 없습니다. 

![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/68376744/6923664c-d154-4941-8b4b-c77104a5dfa6)

현재 내 닉네임으로 중복확인 요청을 보낸다면 API 요청을 보내지 않고 현재 닉네임과 동일하다는 문구를 띄워주고 수정버튼이 계속 활성화되도록 수정해주세요.

### ⚙ 상세한 작업 내용

- [ ] :
- [ ] :
- [ ] : 

### 🛠 예상 소요시간

None

**Comment by junkue20** [comment]
@Wlfjd 
이부분은 기존 닉네임값과 동일하다면 버튼을 아예 비활성화시키는 방식으로 가져가는게 어떨까요
