### ISSUE TITLE
👨‍⚕️ QA: 내가 지원한 커피챗에 신청하기 버튼의 text를 신청완료로 변경 후 버튼 비활성화 요청

### ISSUE THREAD

**Issue by yoonseon12** [Kernel360/f1-JDON-Frontend#210]
<img width="941" alt="image" src="https://github.com/Kernel360/f1-JDON-Frontend/assets/59242594/737eef0b-9354-46a0-9419-aab9df07430e">
현재 내가 참여신청했던 커피챗 상세 화면에서 [신청하기] 버튼을 누르면
<img width="939" alt="image" src="https://github.com/Kernel360/f1-JDON-Frontend/assets/59242594/c812021e-419e-4dac-a041-1b201638b105">
처럼 알림창을 통해 메시지를 출력하고 있습니다. (정상적인 시나리오 입니다.)

---
# 수정 요청
내가 참여 신청한 커피챗 상세화면에 들어오면
<img width="898" alt="image" src="https://github.com/Kernel360/f1-JDON-Frontend/assets/59242594/6f026188-9084-451c-b5ea-54e8b9e1ab15">
이런 식으로 신청완료로 버튼을 표시하고 비활성화 하는 방향이 사용자의 경험적인 측면에서 더 좋을 것 같아요~

**Comment by junkue20** [comment]
![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/122848687/838dbf96-22ea-4426-8ead-0f4a2580ebd8)
반영된것으로 확인되어 닫도록 하겠습니다!
