### ISSUE TITLE
🐛  Fix:  02/29 수정 요청 사항

### ISSUE THREAD

**Issue by Wlfjd** [Kernel360/f1-JDON-Frontend#211]
### ✨ 작업 내용

- jd 상세 정보 줄 구분 
- 로그인 버튼 워딩 수정
- 커피챗 오픈 성공 후 확인 버튼 클릭 시 해당 커피챗 상세 페이지로 이동

### ⚙ 상세한 작업 내용

- [x] : jd 상세 정보 줄 구분 
- [x] : 로그인 버튼 워딩 수정
- [x] : 커피챗 오픈 성공 후 확인 버튼 클릭 시 해당 커피챗 상세 페이지로 이동

### 🛠 예상 소요시간

5시간 이내

**Comment by junkue20** [comment]
로그인 버튼 워딩은 제가 수정했습니다
https://github.com/Kernel360/f1-JDON-Frontend/issues/198
