### ISSUE TITLE
👨‍⚕️ QA: 정렬/필터를 적용한 커피챗 목록페이지의 정렬/필터 상태 유지되지 않음 (~3/17)

### ISSUE THREAD

**Issue by aqrms** [Kernel360/f1-JDON-Frontend#212]
### ✨ 작업 내용

커피챗 목록페이지에서 정렬 또는 필터를 적용하고
![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/111513287/746fd27a-f083-4857-a869-bc6ed83f484b)
상세를 조회한 뒤에
![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/111513287/f3bb86c8-7d94-4d97-8e5f-59ce1d5e157c)
뒤로가기로 목록으로 돌아오면 정렬/필터 상태가 초기화
![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/111513287/bedebdf3-dced-4907-a085-48dbf392fcf3)
사용성을 고려하면 정렬/필터 상태를 유지하는게 어떨까요?

### ⚙ 상세한 작업 내용

- [x] : 커피챗 상세페이지에서 목록 페이지로 돌아올 때 필터 값 유지
- [x] : " 페이지 값 유지

### 🛠 예상 소요시간

None

**Comment by junkue20** [comment]
@Wlfjd 
이부분은 Recoil로 필터값들을 적용하고 관리하는 방법으로 가져가면 좋을 것 같습니다.
다만, 다른 페이지에서 접근시에는 (예를들면 nav버튼 클릭) 전역변수값을 초기화하는식으로 코드를 추가하면 좋겠네요.
