### ISSUE TITLE
👨‍⚕️ QA: 비로그인 상태에서 커피챗 등록 페이지 진입시 리다이렉트 필요

### ISSUE THREAD

**Issue by aqrms** [Kernel360/f1-JDON-Frontend#213]
### ✨ 작업 내용

![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/111513287/90f767da-85b8-458c-85fa-6a9dd84ff694)
비로그인 상태에서도 [+NEW] 버튼을 눌러 등록 페이지에 접근이 가능한데 접근을 막고 로그인으로 리다이렉트가 필요합니다!

### ⚙ 상세한 작업 내용

- [x] : 커피챗 등록 페이지 `privateRoutes`처리

### 🛠 예상 소요시간

None

**Comment by junkue20** [comment]
@aqrms 
해당부분 확인했고, 방금 해결했습니다!
