### ISSUE TITLE
👨‍⚕️ QA: 커피챗 상세 url을 통해 접근한 경우 다른 화면으로 접근 불가

### ISSUE THREAD

**Issue by aqrms** [Kernel360/f1-JDON-Frontend#214]
### ✨ 작업 내용

![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/111513287/15a2d61e-574f-48cf-90d1-88b997392dd9)
URL공유 통해 커피챗 상세로 접근한 경우 다른 화면에 접근할 방법(홈이나 하단 네비바 등)이 없습니다

### ⚙ 상세한 작업 내용

- [ ] :
- [ ] :
- [ ] : 

### 🛠 예상 소요시간

None

**Comment by junkue20** [comment]
@Wlfjd @aqrms 
해당부분 지원님께서 `상세페이지` 경로에는 
nav바가 없는 다른 서비스 레퍼런스들을 참고하셔서 만드셨다고 하셨는데,

해당 레퍼런스를 따르는 부분이시라면, 아래 방향으로 수정하시는건 어떨지 의견이 궁금합니다.
![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/122848687/09e6f399-f06e-437a-b4d5-673a26d0c2cb)

**Comment by aqrms** [comment]
@Wlfjd 
> 해당 이슈는 상단 헤더의 백버튼으로 이동시키는 것을 유도하였습니다. 하단 네비가 매 페이지마다 있는건 좋지 않다고 들어서요! 확인부탁드립니다! 

네 의도하신 바는 확인했습니다! 그런데 A 유저가 커피챗 상세 url을 공유해서 B 유저가 해당 url로 접속한 뒤에 백버튼을 클릭하면 커피챗 목록페이지로 가지 않게됩니다(저의 경우에는 크롬 새탭 페이지로 가네요).

그러므로 url을 직접 수정하는 것 외에는 메인화면으로 갈수 있는 방법도 없기에 해당 페이지에서 다른 서비스를 탐색할 수 없고 이탈하게 될 것 같습니다.

**Comment by Wlfjd** [comment]
아하 공유된 링크로 접속하면 그런 경우도 생길 수 있겠군요
어떻게 하는게 좋을지 준규님과 논의해보겠습니다!

**Comment by junkue20** [comment]
이부분은
https://github.com/Kernel360/f1-JDON-Frontend/issues/240 해당 이슈와 함께 해결이 가능할 것 같습니다!
제가 처리해보도록 하겠습니다
