### ISSUE TITLE
🚨👨‍⚕️ HotQA: 급히 수정되어야 하는 이슈들

### ISSUE THREAD

**Issue by junkue20** [Kernel360/f1-JDON-Frontend#220]
### 해결상황 공유를 위해 작업후 바로 체크표시 부탁드립니다!

🚨 표시는 제가 맡은 내용입니다.

<br/>
<br/>

## ⚙ 상세한 작업 내용

- [x] 🚨0. 404 에러페이지가 없어서 급히 처리해주었습니다.

- [x] 🚨1. `메인페이지 Top 10 키워드` 컴포넌트, `좌 우 화살표`는 화면 크기에 따라 10개가 다 보이지 않을 시에만 화살표가 표시되도록 수정.
   (수정은 하였으나, 현재 이슈가 있어 팀원들과 논의가 필요한 상황.. 탭이 바뀔때마다 컴포넌트가 언마운트되어 생각외로 복잡해짐.. 모바일에서 슬라이드가 가능하니 삭제는 어떤지..?)

- [x] 🚨2. `메인페이지` `JD-ON 더보기 버튼` 지우기.

- [x] 🚨~~3. `Top 10 키워드` `선택값이 유지`되도록 관리가 필요한 것 같음. (`다른페이지를 갔다와도 값이 유지가 되도록.`)~~
   ( 현재 이부분은  `더보기` 버튼 삭제로 메인 페이지는 독자적인 페이지가 됨으로, 굳이 고려하지 않아도 되지 않나 싶음. )

- [x] 🚨4. `JD-ON 목록페이지`, `커피챗 목록페이지` 상단 `도움말 컴포넌트 지우고` 메인페이지처럼 `로고 헤더 적용` 하기
  (`+ JDON 목록페이지 검색input 지우기`)

- [x] 🚨5. oauth2 인증 후 /not-found-email 로 redirect 왔을 때
   `해당 소셜 서비스에 이메일을 등록해야 JDON 서비스를 이용하실 수 있습니다.` 라는 문구를 띄울 것.
   지금 보이는 문구는 마치 서비스 장애 난 것으로 인식됨
- [x] 6-1). `커피챗` 등록하기 버튼 hover 이슈.
(hover 없애도 될 것 같음.)
- [x] 6-2) `커피챗` 등록완료시 `alert 이 뜨도록 수정`, alert창 확인 시 완성된 `방금 작성한 커피챗 상세페이지로 리다이렉트` 되도록 수정 필요.

- [x] 7.`커피챗 등록`일정 등록시 `'!커피챗 날짜는 오늘부터 가능합니다' 라는 잘못된 메세지 수정 필요`.

- [x] 8. `리뷰 상세페이지`의 데이터 정렬은 백엔드쪽에서 수정해서 보내줄 예정이나, 
   `무한스크롤 구현은 현재 백엔드와도 상의가 필요`한 부분.

- [x] 9. `alert , 유효성 검사 에러 메세지 형식`들을 `통일할 필요`가 있어보임..
   (request 보내기 전에는 프론트에서 공통된 양식의 메세지를 사용,
   request 보냈을 때 에러가 발생한다면 서버에서 response로 전달받은 에러 메시지를 활용하는 것도 고려)

- [x] 10-1). `커피챗 등록화면`, `리뷰 등록화면`의 input 컴포넌트별로 `텍스트 최대길이 제한` 필요. (유효성 검사 추가할 것. )
- [x] 10-2). `커피챗 상페페이지`에 content내용이 줄바꿈이 없을 시` 화면을 뚫고 나가는 오류`가 있음. 수정 필요.

- [x] 🚨11. `회원가입 시` 닉네임에 `관리자, 어드민, admin, administer` 이라는 키워드는 포함되지 못하도록 개별 유효성 검사 추가하기. 
  (추가로 띄어쓰기나 특수기호도 포함되지 못하도록 했습니다.)

**Comment by corazzon** [comment]
<img width="1299" alt="image" src="https://github.com/Kernel360/f1-JDON-Frontend/assets/1324021/4d826d2e-45a4-414a-b060-534a48b36d05">

제목 글자길이 체크에 대한 서버 응답을 보여주세요. 커피챗 등록시 제목이 길면 아무런 액션이 보이지 않습니다.

**Comment by aqrms** [comment]
> <img alt="image" width="1299" src="https://private-user-images.githubusercontent.com/1324021/309611977-4d826d2e-45a4-414a-b060-534a48b36d05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MjQ1NTYsIm5iZiI6MTcwOTUyNDI1NiwicGF0aCI6Ii8xMzI0MDIxLzMwOTYxMTk3Ny00ZDgyNmQyZS00NWE0LTQxNGEtYjA2MC01MzRhNDhiMzZkMDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMDM1MDU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDhhNDQzYTVmZjZkYzkxZDRhNDNjNzg3MmEyN2Y2YjEyMWI2MTYzOGMxMDgwNGM0M2U5MGZlNDBiZmQ1MDkyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0bYUtsWv4Rsoyhk5lbr5vnd33Y9PucGQUNUr7xGujKI">
> 제목 글자길이 체크에 대한 서버 응답을 보여주세요. 커피챗 등록시 제목이 길면 아무런 액션이 보이지 않습니다.

관련해서 #228로 이슈 등록하였습니다! HotQA로 관리부탁드립니다!

**Comment by corazzon** [comment]
<img width="1198" alt="image" src="https://github.com/Kernel360/f1-JDON-Frontend/assets/1324021/3d627355-966f-49ba-a05e-b298468dbe84">
일시가 입력되어 있지 않을 때 경고 메시지 없이 서버 오류가 납니다.

**Comment by corazzon** [comment]
<img width="723" alt="image" src="https://github.com/Kernel360/f1-JDON-Frontend/assets/1324021/a35b66e0-7d47-4356-acdc-c264625708d8">
날짜만 선택했을 때 값이 입력된 것으로 되어 커피챗 등록이 되고 valid check 에서 문자일 때 입력이 되지 않도록 개선이 필요합니다.

**Comment by corazzon** [comment]
<img width="1253" alt="image" src="https://github.com/Kernel360/f1-JDON-Frontend/assets/1324021/b7ad93a6-bddc-47ed-9a08-bc662df81d22">

내용 수정시 과거 날짜에서 서버 오류 메시지를 프론트에서 보여주지 않고 수정이 되지 않는 문제

**Comment by junkue20** [comment]
@corazzon 
디렉터님께서 주신 사항은 https://github.com/Kernel360/f1-JDON-Frontend/issues/254 번 이슈에 등록했습니다!
