### ISSUE TITLE
👨‍⚕️ QA: 마이 페이지의 찜 화면에서 새로고침하면 로그인 정보가 날라가는 것 같음 

### ISSUE THREAD

**Issue by anso33** [Kernel360/f1-JDON-Frontend#225]
### ✨ 작업 내용

<img width="1387" alt="image" src="https://github.com/Kernel360/f1-JDON-Frontend/assets/68376744/dd462cca-22e1-4256-a5de-6cbf173b4586">

여기서 바로 새로고침하면
<img width="1367" alt="image" src="https://github.com/Kernel360/f1-JDON-Frontend/assets/68376744/8032bbed-b4a3-4edd-9463-bb8dfd6ed87e">

다시 로그인하라고 뜹니다

### ⚙ 상세한 작업 내용

- [ ] :
- [ ] :
- [ ] : 

### 🛠 예상 소요시간

None

**Comment by anso33** [comment]
여기서 뿐만 아니라 마이페이지에서 새로고침을 해도 로그인해야한다는 alert 창이 뜨네요

**Comment by junkue20** [comment]
해결 완료했습니다
