### ISSUE TITLE
👨‍⚕️ QA: 커피챗 생성 성공하고 난 후 오류페이지가 보임 

### ISSUE THREAD

**Issue by anso33** [Kernel360/f1-JDON-Frontend#226]
### ✨ 작업 내용

커피챗을 생성 성공하고 난 후 새로 요청되는 것 같은  url에 값이 잘못들어가는 것 같아요

커피챗 생성하고 난 후 보이는 페이지 (사진 속 url 확인 부탁드립니다.)

<img width="1392" alt="image" src="https://github.com/Kernel360/f1-JDON-Frontend/assets/68376744/b31bfc9e-d97c-4066-a130-4db7aac271cf">

### ⚙ 상세한 작업 내용

- [ ] :
- [ ] :
- [ ] : 

### 🛠 예상 소요시간

None

**Comment by Wlfjd** [comment]
해결하였습니다
