### ISSUE TITLE
👨‍⚕️ QA: 커피챗과 리뷰를  등록 or 수정하는 post 요청시 body에 담는 값 Validation 적용

### ISSUE THREAD

**Issue by aqrms** [Kernel360/f1-JDON-Frontend#228]
### ✨ 작업 내용

커피챗과 리뷰를 등록,수정 하는 post요청에서 동작별로 아래와 같이 Validation을 적용했습니다.
해당 기준 미준수 시 400 에러 응답이 나가게 되므로 프론트에서도 Validation 처리 반영 부탁드립니다!
각 API 명세에도 반영해 놓았습니다. 에러메세지 참조하셔서 그대로 반영될 수 있도록 확인 부탁드립니다.

- 커피챗 (등록, 수정)
  - 제목
    - 10자 이상 50자 이하 
  - 내용
    -  50자 이상 500자 이하
  - 모집인원
    - 1명 이상 100명 이하 
  - 일시
    - 현재보다 미래 시점
  -  오픈채팅 링크
     - URL 형식 준수
 - 리뷰 (등록)
   - 내용
     -  10자 이상 500자 이하

https://www.notion.so/88e4293db39e407692719b94673cdef1?pvs=4
커피챗 (등록,수정 동일)
![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/111513287/6e26428f-5965-4e50-b217-42e694880159)
리뷰 (등록)
![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/111513287/2057f02d-bc61-4124-a023-8333be468c11)

### ⚙ 상세한 작업 내용

- [ ] :
- [ ] :
- [ ] : 

### 🛠 예상 소요시간

None

**Comment by Wlfjd** [comment]
Validation 적용 완료하였습니다
