### ISSUE TITLE
👨‍⚕️ QA: 회원가입시 생일에 대한 날짜 에러

### ISSUE THREAD

**Issue by anso33** [Kernel360/f1-JDON-Frontend#229]
### ✨ 작업 내용

API 명세상 2023-01-01 의 형식으로 보내야하는데
 
![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/68376744/f88d9e41-f71c-4823-9061-2e18153833ec)

요청 보낼 때 LocalDateTime 으로 보내는 것 같아요!

![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/68376744/c0f038f2-d571-411a-93a7-cf72fa9f3e25)

### ⚙ 상세한 작업 내용

- [ ] :
- [ ] :
- [ ] : 

### 🛠 예상 소요시간

None

**Comment by Wlfjd** [comment]
해결했습니다 
확인 부탁드려요~
