### ISSUE TITLE
👨‍⚕️ QA: 커피챗 상세화면에서 목록버튼 추가 요청

### ISSUE THREAD

**Issue by yoonseon12** [Kernel360/f1-JDON-Frontend#240]
### 커피챗 상세 페이지에서 목록으로 갈 수 있는 버튼 추가
은종 디렉터님께서 커피챗 상세 페이지에서 목록으로 갈 수 있는 버튼이 추가되었으면 좋겠다고 하셨습니다.
<img width="265" alt="image" src="https://github.com/Kernel360/f1-JDON-Frontend/assets/59242594/90e14bd4-890a-4aeb-a48d-f9f6916810f8">
**커피챗 목록에서 상세페이지로 접근했을 경우 위와 같이 `<` 버튼을 클릭해서 이전페이지로 갈 수는 있으나
커피챗 등록 후 상세페이지로 접근했을때는 `<` 버튼을 클릭하면 커피챗 등록 폼으로 돌아가서 목록으로 가기 어렵습니다.**
- 위에대한 제 개인적인 생각은 커피챗 등록 후 상세페이지로 접근 후 `<` 버튼을 클릭하면 '이미 작성한 커피챗 정보입니다.' 라는 알림창을 띄워서 못가게 막으면 어떨까요?(등록폼으로 이동하는게 장애는 아니지만 굳이 작성폼으로 돌아갈 필요가 없다고 생각되네요.)

어디에서 접근했든 목록으로 가는 버튼이 있으면 사용자 관점에서 더 편리할 것 같다는 의견을 주셔서 반영이 필요할 것 같아요.

### 또한 이전 페이지의 상태로 이동할 수 있도록 반영이 필요합니다.
예를들어 2페이지에 있는 커피챗을 들어가고 뒤로가기 버튼을 클릭 or 목록 버튼을 클릭했을 때 2페이지로 이동하도록 구현해야합니다.
현재 존재하는 뒤로가기버튼은 2페이지에서 접근했어도 1페이지로 이동시키고 있어요. 상태를 저장하고 있지 않기 때문인 것 같네요

**Comment by junkue20** [comment]
이부분은 제가 수정할 예정입니다!
