### ISSUE TITLE
👨‍⚕️ QA: 회원 정보 수정시 올바르지 않은 날짜 정보에 대한 유효성 검사가 진행되지 않는 이슈 (~3/13)

### ISSUE THREAD

**Issue by junkue20** [Kernel360/f1-JDON-Frontend#279]
### ✨ 작업 내용

api는 정상적으로 호출 하는데 화면에서 아무런 처리를 하지 않는듯 함.

### ⚙ 상세한 작업 내용

- [x] : 회원정보 수정된 날짜에 대한 프론트 유효성 검사 필요
- [ ] :
- [ ] : 

### 🛠 예상 소요시간

None

**Comment by Wlfjd** [comment]
문제 없는거 확인했습니다!
