### ISSUE TITLE
👨‍⚕️ QA: 커피챗 생성 페이지에서 사용자의 직무를 파악할 수 있는 ui가 필요함. (~3/13)

### ISSUE THREAD

**Issue by junkue20** [Kernel360/f1-JDON-Frontend#286]
### ✨ 작업 내용

현재 해당 화면에서 작성자가 자신의 직무 `백, 프론트`를 확인할 수 있는 수단이 존재X.
![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/122848687/d096bbf3-fdbd-4c52-a281-0cae44fc07b5)

해당 페이지에서 현재 사용자가 백, 프론트인지 알 수 있는 ui가 필요. 
#### 그리고 해당 직무는 마이페이지에서 수정 가능하다는 도움말도 추가하면 좋을듯 함.

---

![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/122848687/3f325111-4d83-4fe1-9d32-1f80af96c116)

개인적으로 해당 사진에 표시된 위치에 `프론트, 서버개발자` 아이콘을 재사용하는건 어떤지 의견을 여쭤보고 싶습니다.

### ⚙ 상세한 작업 내용

- [ ] : 커피챗 생성화면 작성자 직무 관련 가이드 UI 생성

### 🛠 예상 소요시간

None

**Comment by aqrms** [comment]
저는 대략 이런 느낌을 생각했어요 
![image](https://github.com/Kernel360/f1-JDON-Frontend/assets/111513287/7171580c-1a18-40a7-a699-f35a568908e9)
